# Generated by Django 3.2.7 on 2021-09-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='type',
            field=models.CharField(choices=[('G', 'Gym'), ('Y', 'Yoga'), ('D', 'Dance')], default=('G', 'Gym'), max_length=255),
        ),
    ]
